### ISSUE TITLE
Update zen browser to a.22

### ISSUE THREAD

**Issue by BlueFox1616** [0xc000022070/zen-browser-flake#8]
What the title says

**Comment by luisnquin** [comment]
It looks like the CI is failing with the new release.

I will investigate and fix this today.

**Comment by luisnquin** [comment]
This was fixed with commit https://github.com/0xc000022070/zen-browser-flake/commit/5c342274b37fc1ed8a9d2770fde3f53b489b2067. Thanks for the report.
